"use client";

import Link from "next/link";
import { DragEvent, FormEvent, useState } from "react";
import { DemoBadge, Heading } from "./workspace-shell";
import { initialColumns, initialTasks, newsItems, Priority, Task } from "@/lib/workspace";

const Panel = ({ children }: { children: React.ReactNode }) => <section className="panel feature-panel">{children}</section>;

export function Dashboard() { return <><Heading eyebrow="PROJECT OVERVIEW" title="Good morning, Tajime" text="สิ่งสำคัญใน DEV LIFE วันนี้" action={<Link className="primary link-button" href="/notes">＋ New note</Link>} /><div className="stats">{[["Active tasks","2","2 high priority"],["Open pull requests","3","Demo data"],["Beta progress","68%","18 days remaining"],["Inbox","7","Unsorted captures"]].map(x => <article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>)}</div><div className="dashboard-grid"><Panel><h2>Focus next</h2>{initialTasks.map(t => <div className="focus-row" key={t.id}><span className={t.done ? "check done" : "check"}>{t.done ? "✓" : ""}</span><div><b>{t.title}</b><small>{t.priority} priority</small></div></div>)}</Panel><section className="ai-card"><small>✦ AI PROJECT BRIEF · DEMO</small><h2>แผนพร้อมเดินหน้า แต่ยังมี 2 จุดเสี่ยง</h2><p>Onboarding ยังไม่มี accessibility checklist และ beta metrics ยังไม่ชัดเจน</p><Link href="/ai-tools">Review demo preview</Link></section></div></>; }

export function Notes() { const [note,setNote]=useState("# DEV LIFE Beta\n\nสร้าง workspace ที่เชื่อมความคิด งาน และบริบทไว้ในที่เดียว"); const [versions,setVersions]=useState([{id:1,text:note,at:"10:12"}]); return <><Heading eyebrow="NOTE EDITOR" title="Beta launch plan" text="Frontend-only local state" action={<button onClick={() => setVersions(x => [{id:Date.now(),text:note,at:new Date().toLocaleTimeString("th-TH")},...x])}>Save version</button>} /><div className="notes-grid"><section className="panel feature-panel editor"><div className="toolbar"><button><b>B</b></button><button>H1</button><button>• List</button><button>{"</>"}</button></div><textarea aria-label="เนื้อหาโน้ต" className="note-editor" value={note} onChange={e=>setNote(e.target.value)} /></section><Panel><h2>Version history</h2><div className="history">{versions.map(v=><button key={v.id} onClick={()=>setNote(v.text)}><span><b>Beta launch plan</b><small>{v.at}</small></span><em>Restore</em></button>)}</div></Panel></div></>; }

export function Checklists() { const [tasks,setTasks]=useState<Task[]>(initialTasks); const [title,setTitle]=useState(""); const [priority,setPriority]=useState<Priority>("กลาง"); const add=(e:FormEvent)=>{e.preventDefault();if(title.trim()){setTasks(x=>[...x,{id:Date.now(),title,done:false,priority}]);setTitle("")}}; return <><Heading eyebrow="TASK PLANNING" title="Project checklist" text="แบ่งงาน ติดตามความคืบหน้า และกำหนด priority" /><Panel><div className="checklist">{tasks.map(t=><div className="task" key={t.id}><input type="checkbox" checked={t.done} onChange={()=>setTasks(x=>x.map(y=>y.id===t.id?{...y,done:!y.done}:y))}/><span className={t.done?"strike":""}>{t.title}</span><em className={`priority p-${t.priority}`}>{t.priority}</em></div>)}<form className="task-form" onSubmit={add}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="เพิ่มรายการ..."/><select value={priority} onChange={e=>setPriority(e.target.value as Priority)}><option>สูง</option><option>กลาง</option><option>ต่ำ</option></select><button>Add</button></form></div></Panel></>; }

export function Board() { const [columns,setColumns]=useState(initialColumns); const move=(e:DragEvent,target:keyof typeof columns)=>{e.preventDefault();const id=Number(e.dataTransfer.getData("card"));let card;for(const cards of Object.values(columns)) card ||= cards.find(x=>x.id===id);if(card)setColumns(Object.fromEntries(Object.entries(columns).map(([key,cards])=>[key,key===target?[...cards.filter(x=>x.id!==id),card]:cards.filter(x=>x.id!==id)])) as typeof columns)}; return <><Heading eyebrow="PROJECT BOARD" title="Beta launch" text="ลาก card เพื่ออัปเดตสถานะงาน"/><div className="kanban">{(Object.keys(columns) as (keyof typeof columns)[]).map(col=><section key={col} onDragOver={e=>e.preventDefault()} onDrop={e=>move(e,col)}><div className="column-title"><h2>{col}</h2><span>{columns[col].length}</span></div>{columns[col].map(c=><article draggable onDragStart={e=>e.dataTransfer.setData("card",String(c.id))} key={c.id}><small>{c.tag}</small><b>{c.title}</b><span>DEV LIFE · วันนี้</span></article>)}</section>)}</div></>; }

export function Flowchart() { const [nodes,setNodes]=useState(["Start","Capture idea","Review","Done"]); const [selected,setSelected]=useState(1); return <><Heading eyebrow="SIMPLE FLOWCHART" title="Inbox processing flow" text="เพิ่ม เลือก และแก้ไข node ได้ใน local state" action={<button onClick={()=>{setNodes(x=>[...x,"New process"]);setSelected(nodes.length)}}>＋ Add node</button>}/><section className="flow panel"><div className="flow-canvas">{nodes.map((n,i)=><div className="flow-step" key={i}><button className={selected===i?"selected":""} onClick={()=>setSelected(i)}>{n}</button>{i<nodes.length-1&&<span>↓</span>}</div>)}</div><aside><h2>Node properties</h2><label>Label<input value={nodes[selected]} onChange={e=>setNodes(x=>x.map((n,i)=>i===selected?e.target.value:n))}/></label><button onClick={()=>{setNodes(x=>x.filter((_,i)=>i!==selected));setSelected(0)}}>Remove node</button></aside></section></>; }

export function Templates() { const [used,setUsed]=useState(""); const list=["Feature specification","Bug investigation","API design","Sprint board","PR review checklist","Release plan"]; return <><Heading eyebrow="TEMPLATE LIBRARY" title="เริ่มงานด้วยโครงสร้างที่ดี" text="เลือกแม่แบบเพื่อสร้าง draft frontend-only"/>{used&&<Panel><b>Draft created: {used}</b><p># Context · Goals · Details · Checklist</p></Panel>}<div className="template-grid">{list.map(x=><article className="panel" key={x}><span>◫</span><h2>{x}</h2><p>Context, goals, details และ checklist ที่พร้อมเริ่มกรอก</p><button onClick={()=>setUsed(x)}>Use template →</button></article>)}</div></>; }

export function Search() { const [q,setQ]=useState(""); const items=[...initialTasks.map(x=>({title:x.title,type:"Task"})),...newsItems.map(x=>({title:x.title,type:"News Demo"})),{title:"Beta launch plan",type:"Note"},{title:"PR #42 Onboarding",type:"GitHub Demo"}]; const found=items.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())); return <><Heading eyebrow="UNIVERSAL SEARCH" title="ค้นหาทั้ง workspace" text="ค้นหา mock workspace data โดยไม่เรียก API"/><Panel><input className="large-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา note, task, PR หรือข่าว..."/>{found.map(x=><div className="search-row" key={x.title}><b>{x.title}</b><small>{x.type}</small></div>)}</Panel></>; }

export function Inbox() { const [text,setText]=useState(""); const [items,setItems]=useState(["ลองทำ keyboard-first onboarding","Error boundary strategy"]); return <><Heading eyebrow="CAPTURE BOX" title="Inbox" text="เก็บไอเดียไว้จัดระเบียบภายหลัง"/><section className="capture panel"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="วางไอเดีย ลิงก์ หรือ error..."/><button className="primary" onClick={()=>{if(text.trim()){setItems(x=>[text,...x]);setText("")}}}>Capture</button></section><Panel>{items.map((x,i)=><div className="search-row" key={x}><b>{x}</b><button onClick={()=>setItems(y=>y.filter((_,j)=>j!==i))}>Convert to task</button></div>)}</Panel></>; }

export function Activity() { return <><Heading eyebrow="PROJECT HISTORY" title="Activity timeline" text="ประวัติ demo ของการเปลี่ยนแปลงใน workspace"/><Panel><div className="timeline">{["แก้ไข Beta launch plan","ย้าย Onboarding flow ไป Review","บันทึกข่าว React ลง note","สร้าง accessibility checklist"].map((x,i)=><div key={x}><span/><section><b>{x}</b><small>{i+1} ชั่วโมงที่แล้ว · Demo activity</small></section></div>)}</div></Panel></>; }

export function ContextMap() { const [active,setActive]=useState("Beta launch plan"); const nodes=["Beta launch plan","Onboarding flow","PR #42","Issue #51"]; return <><Heading eyebrow="PROJECT MEMORY" title="Context map" text="สำรวจความสัมพันธ์ของ note, task และ repository demo"/><section className="context-map panel">{nodes.map((x,i)=><div key={x}>{i>0&&<span>connected to</span>}<button className={active===x?"active":""} onClick={()=>setActive(x)}>{x}</button></div>)}<p>Selected: {active}</p></section></>; }

export function AITools() { const [preview,setPreview]=useState(false); const [applied,setApplied]=useState(false); return <><Heading eyebrow="AI ASSISTANT" title="AI planning tools" text="Demo เท่านั้น · ไม่มีการเรียก AI API" action={<DemoBadge/>}/><div className="dashboard-grid"><Panel><h2>Ask project</h2><p>สถานะโปรเจกต์ตอนนี้มีความเสี่ยงอะไร?</p><button onClick={()=>setPreview(true)}>Generate demo preview</button></Panel><Panel><h2>Risk check</h2><p>ตรวจ scope, requirement, test checklist และ dependency จาก mock context</p><button onClick={()=>setPreview(true)}>Run demo check</button></Panel></div>{preview&&<div className="modal-layer"><section className="ai-modal"><h2>AI change preview · Demo</h2><p>เสนอเพิ่ม accessibility audit และกำหนด beta success metrics</p><div className="change"><b>＋ ADD TASK</b><small>ยังไม่มีข้อมูลใดถูกส่งออกจาก browser</small></div><footer><button onClick={()=>setPreview(false)}>Reject</button><button className="primary" onClick={()=>{setApplied(true);setPreview(false)}}>Apply locally</button></footer></section></div>}{applied&&<Panel><b>Applied to local demo state</b></Panel>}</>; }

export function Github() { const [tab,setTab]=useState("Pull requests"); const rows:Record<string,string[]>={"Pull requests":["#42 Add onboarding experience","#39 Refine note editor layout"],Issues:["#51 Keyboard navigation","#48 Empty states"],Commits:["a81c6d2 Improve navigation","5c9fe10 Add editor"],Branches:["main","feature/onboarding"]}; return <><Heading eyebrow="GITHUB / READ-ONLY DEMO" title="dev-life / workspace" text="Mock data เท่านั้น · ไม่มี API · ไม่สามารถสร้างหรือ merge PR" action={<DemoBadge>Demo · Read-only · รอเชื่อมต่อ</DemoBadge>}/><div className="tabs">{Object.keys(rows).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><Panel><h2>{tab}</h2>{rows[tab].map(x=><div className="search-row" key={x}><b>{x}</b><small>Demo repository data</small></div>)}</Panel></>; }

export function News() { const [filter,setFilter]=useState("ทั้งหมด"); const [saved,setSaved]=useState<number[]>([]); const items=filter==="ทั้งหมด"?newsItems:newsItems.filter(x=>x.tag===filter); return <><Heading eyebrow="DEV NEWS · DEMO" title="อัปเดตที่ควรรู้" text="Mock summaries · ไม่มี RSS/API call" action={<DemoBadge/>}/><div className="filters">{["ทั้งหมด","AI","Web","Security"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="news-grid">{items.map(x=><article className="panel" key={x.id}><small>{x.source} · {x.tag}</small><h2>{x.title}</h2><p>{x.summary}</p><button onClick={()=>setSaved(y=>[...new Set([...y,x.id])])}>{saved.includes(x.id)?"✓ Saved locally":"＋ Save locally"}</button></article>)}</div></>; }
