"use client";

import Link from "next/link";
import { DragEvent, FormEvent, useState } from "react";
import { Badge, Button, Card, EmptyState, FormField, Input, Modal, Select, Tabs, Textarea, useToast } from "@/components/ui";
import { DemoBadge, Heading } from "./workspace-shell";
import { initialColumns, initialTasks, newsItems, Priority, Task } from "@/lib/workspace";

const Panel = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <Card className={`feature-panel ${className}`}>{children}</Card>;

export function Dashboard() { return <><section className="project-hero"><div><Badge tone="success">IN DEVELOPMENT</Badge><h1>DEV LIFE Beta</h1><p>Developer workspace ที่เชื่อม notes, tasks และ project context ไว้ในที่เดียว</p></div><div className="hero-actions"><Link href="/notes">Open notes</Link><Link className="primary link-button" href="/inbox">Quick capture</Link></div></section><nav className="project-tabs" aria-label="Project sections"><Link className="active" href="/dashboard">Overview</Link><Link href="/notes">Notes</Link><Link href="/checklists">Tasks</Link><Link href="/activity">Activity</Link></nav><div className="cockpit-grid"><Card className="cockpit-main"><div className="section-head"><div><span>TODAY</span><h2>Current focus</h2></div><Link href="/checklists">View all tasks</Link></div><div className="focus-list">{initialTasks.map((task,index) => <article key={task.id}><span className={task.done ? "task-index done" : "task-index"}>{task.done ? "✓" : String(index + 1).padStart(2,"0")}</span><div><b>{task.title}</b><small>{task.done ? "Completed" : `${task.priority} priority · DEV LIFE Beta`}</small></div><Badge tone={task.priority === "สำคัญมาก" ? "danger" : task.priority === "สำคัญ" ? "warning" : "success"}>{task.priority}</Badge></article>)}</div><div className="section-head activity-head"><div><span>RECENT</span><h2>Project activity</h2></div><Link href="/activity">Full history</Link></div><div className="compact-activity"><article><i>NT</i><div><b>Beta launch plan updated</b><small>Note edited · 32 minutes ago</small></div></article><article><i>TS</i><div><b>Onboarding flow moved to Review</b><small>Task status changed · 2 hours ago</small></div></article></div></Card><aside className="cockpit-side"><Card className="project-health"><div className="section-head"><div><span>PROJECT HEALTH</span><h2>On track</h2></div><strong>68%</strong></div><div className="progress"><i /></div><dl><div><dt>Open tasks</dt><dd>2</dd></div><div><dt>In review</dt><dd>1</dd></div><div><dt>Decisions</dt><dd>3</dd></div></dl></Card></aside></div></>; }

export function Notes() { const [note,setNote]=useState("# DEV LIFE Beta\n\nสร้าง workspace ที่เชื่อมความคิด งาน และบริบทไว้ในที่เดียว"); const [versions,setVersions]=useState([{id:1,text:note,at:"10:12"}]); return <><Heading eyebrow="NOTE EDITOR" title="Beta launch plan" text="Frontend-only local state" action={<Button variant="primary" onClick={() => setVersions(x => [{id:Date.now(),text:note,at:new Date().toLocaleTimeString("th-TH")},...x])}>Save version</Button>} /><div className="notes-grid"><Panel className="editor"><div className="toolbar"><Button variant="ghost" size="sm"><b>B</b></Button><Button variant="ghost" size="sm">H1</Button><Button variant="ghost" size="sm">• List</Button><Button variant="ghost" size="sm">{"</>"}</Button></div><Textarea aria-label="เนื้อหาโน้ต" className="note-editor" value={note} onChange={event=>setNote(event.target.value)} /></Panel><Panel><h2>Version history</h2><div className="history">{versions.map(version=><Button variant="ghost" key={version.id} onClick={()=>setNote(version.text)}><span><b>Beta launch plan</b><small>{version.at}</small></span><em>Restore</em></Button>)}</div></Panel></div></>; }

export function Checklists() { const [tasks,setTasks]=useState<Task[]>(initialTasks); const [title,setTitle]=useState(""); const [priority,setPriority]=useState<Priority>("ทั่วไป"); const add=(event:FormEvent)=>{event.preventDefault();if(title.trim()){setTasks(current=>[...current,{id:Date.now(),title,done:false,priority}]);setTitle("")}}; return <><Heading eyebrow="TASK PLANNING" title="Project checklist" text="แบ่งงาน ติดตามความคืบหน้า และกำหนด priority" /><Panel><div className="checklist">{tasks.map(task=><div className="task" key={task.id}><input aria-label={`ทำเครื่องหมาย ${task.title}`} type="checkbox" checked={task.done} onChange={()=>setTasks(current=>current.map(item=>item.id===task.id?{...item,done:!item.done}:item))}/><span className={task.done?"strike":""}>{task.title}</span><Badge tone={task.priority === "สำคัญมาก" ? "danger" : task.priority === "สำคัญ" ? "warning" : "success"}>{task.priority}</Badge></div>)}<form className="task-form" onSubmit={add}><Input aria-label="ชื่องาน" value={title} onChange={event=>setTitle(event.target.value)} placeholder="เพิ่มรายการ..."/><Select aria-label="ความสำคัญ" value={priority} onChange={event=>setPriority(event.target.value as Priority)}><option>สำคัญมาก</option><option>สำคัญ</option><option>ทั่วไป</option></Select><Button variant="primary">Add</Button></form></div></Panel></>; }

export function Board() { const [columns,setColumns]=useState(initialColumns); const move=(event:DragEvent,target:keyof typeof columns)=>{event.preventDefault();const id=Number(event.dataTransfer.getData("card"));let card;for(const cards of Object.values(columns)) card ||= cards.find(item=>item.id===id);if(card)setColumns(Object.fromEntries(Object.entries(columns).map(([key,cards])=>[key,key===target?[...cards.filter(item=>item.id!==id),card]:cards.filter(item=>item.id!==id)])) as typeof columns)}; return <><Heading eyebrow="PROJECT BOARD" title="Beta launch" text="ลาก card เพื่ออัปเดตสถานะงาน"/><div className="kanban">{(Object.keys(columns) as (keyof typeof columns)[]).map(column=><Card key={column} onDragOver={undefined}><div className="column-title"><h2>{column}</h2><Badge>{columns[column].length}</Badge></div><div onDragOver={event=>event.preventDefault()} onDrop={event=>move(event,column)}>{columns[column].map(card=><Card as="article" draggable onDragStart={event=>event.dataTransfer.setData("card",String(card.id))} key={card.id}><Badge tone="brand">{card.tag}</Badge><b>{card.title}</b><span>DEV LIFE · วันนี้</span></Card>)}</div></Card>)}</div></>; }

export function Flowchart() { const [nodes,setNodes]=useState(["Start","Capture idea","Review","Done"]); const [selected,setSelected]=useState(1); return <><Heading eyebrow="SIMPLE FLOWCHART" title="Inbox processing flow" text="เพิ่ม เลือก และแก้ไข node ได้ใน local state" action={<Button variant="primary" onClick={()=>{setNodes(current=>[...current,"New process"]);setSelected(nodes.length)}}>＋ Add node</Button>}/><Card className="flow"><div className="flow-canvas">{nodes.map((node,index)=><div className="flow-step" key={index}><Button className={selected===index?"selected":""} onClick={()=>setSelected(index)}>{node}</Button>{index<nodes.length-1&&<span>↓</span>}</div>)}</div><aside><h2>Node properties</h2><FormField label="Label"><Input value={nodes[selected]} onChange={event=>setNodes(current=>current.map((node,index)=>index===selected?event.target.value:node))}/></FormField><Button variant="danger" onClick={()=>{setNodes(current=>current.filter((_,index)=>index!==selected));setSelected(0)}}>Remove node</Button></aside></Card></>; }

export function Templates() { const [used,setUsed]=useState(""); const list=["Feature specification","Bug investigation","API design","Sprint board","PR review checklist","Release plan"]; return <><Heading eyebrow="TEMPLATE LIBRARY" title="เริ่มงานด้วยโครงสร้างที่ดี" text="เลือกแม่แบบเพื่อสร้าง draft frontend-only"/>{used&&<Panel><b>Draft created: {used}</b><p># Context · Goals · Details · Checklist</p></Panel>}<div className="template-grid">{list.map(item=><Card as="article" key={item}><span>◫</span><h2>{item}</h2><p>Context, goals, details และ checklist ที่พร้อมเริ่มกรอก</p><Button variant="ghost" onClick={()=>setUsed(item)}>Use template →</Button></Card>)}</div></>; }
export function Search() { const [query,setQuery]=useState(""); const items=[...initialTasks.map(item=>({title:item.title,type:"Task"})),...newsItems.map(item=>({title:item.title,type:"News Demo"})),{title:"Beta launch plan",type:"Note"},{title:"PR #42 Onboarding",type:"GitHub Demo"}]; const found=items.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())); return <><Heading eyebrow="UNIVERSAL SEARCH" title="ค้นหาทั้ง workspace" text="ค้นหา mock workspace data โดยไม่เรียก API"/><Panel><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ค้นหา note, task, PR หรือข่าว..."/>{found.map(item=><div className="search-row" key={item.title}><b>{item.title}</b><Badge>{item.type}</Badge></div>)}{!found.length&&<EmptyState title="ไม่พบผลลัพธ์" description="ลองใช้คำค้นหาอื่น"/>}</Panel></>; }
export function Inbox() { const [text,setText]=useState(""); const [items,setItems]=useState(["ลองทำ keyboard-first onboarding","Error boundary strategy"]); return <><Heading eyebrow="CAPTURE BOX" title="Inbox" text="เก็บไอเดียไว้จัดระเบียบภายหลัง"/><Card className="capture"><Textarea value={text} onChange={event=>setText(event.target.value)} placeholder="วางไอเดีย ลิงก์ หรือ error..."/><Button variant="primary" onClick={()=>{if(text.trim()){setItems(current=>[text,...current]);setText("")}}}>Capture</Button></Card><Panel>{items.map((item,index)=><div className="search-row" key={item}><b>{item}</b><Button variant="ghost" onClick={()=>setItems(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>Convert to task</Button></div>)}{!items.length&&<EmptyState title="Inbox ว่างแล้ว"/>}</Panel></>; }
export function Activity() { return <><Heading eyebrow="PROJECT HISTORY" title="Activity timeline" text="ประวัติ demo ของการเปลี่ยนแปลงใน workspace"/><Panel><div className="timeline">{["แก้ไข Beta launch plan","ย้าย Onboarding flow ไป Review","บันทึกข่าว React ลง note","สร้าง accessibility checklist"].map((item,index)=><div key={item}><span/><section><b>{item}</b><small>{index+1} ชั่วโมงที่แล้ว · Demo activity</small></section></div>)}</div></Panel></>; }
export function ContextMap() { const [active,setActive]=useState("Beta launch plan"); const nodes=["Beta launch plan","Onboarding flow","PR #42","Issue #51"]; return <><Heading eyebrow="PROJECT MEMORY" title="Context map" text="สำรวจความสัมพันธ์ของ note, task และ repository demo"/><Card className="context-map">{nodes.map((node,index)=><div key={node}>{index>0&&<span>connected to</span>}<Button className={active===node?"active":""} onClick={()=>setActive(node)}>{node}</Button></div>)}<Badge tone="brand">Selected: {active}</Badge></Card></>; }
export function AITools() { const [preview,setPreview]=useState(false); const [applied,setApplied]=useState(false); return <><Heading eyebrow="AI ASSISTANT" title="AI planning tools" text="Demo เท่านั้น · ไม่มีการเรียก AI API" action={<DemoBadge/>}/><div className="dashboard-grid"><Panel><h2>Ask project</h2><p>สถานะโปรเจกต์ตอนนี้มีความเสี่ยงอะไร?</p><Button onClick={()=>setPreview(true)}>Generate demo preview</Button></Panel><Panel><h2>Risk check</h2><p>ตรวจ scope, requirement, test checklist และ dependency จาก mock context</p><Button onClick={()=>setPreview(true)}>Run demo check</Button></Panel></div><Modal open={preview} onClose={()=>setPreview(false)} title="AI change preview · Demo" description="เสนอเพิ่ม accessibility audit และกำหนด beta success metrics" footer={<><Button onClick={()=>setPreview(false)}>Reject</Button><Button variant="primary" onClick={()=>{setApplied(true);setPreview(false)}}>Apply locally</Button></>}><Card className="change"><b>＋ ADD TASK</b><small>ยังไม่มีข้อมูลใดถูกส่งออกจาก browser</small></Card></Modal>{applied&&<Panel><b>Applied to local demo state</b></Panel>}</>; }
export function Github() { const [tab,setTab]=useState("Pull requests"); const rows:Record<string,string[]>={"Pull requests":["#42 Add onboarding experience","#39 Refine note editor layout"],Issues:["#51 Keyboard navigation","#48 Empty states"],Commits:["a81c6d2 Improve navigation","5c9fe10 Add editor"],Branches:["main","feature/onboarding"]}; return <><Heading eyebrow="GITHUB / READ-ONLY DEMO" title="dev-life / workspace" text="Mock data เท่านั้น · ไม่มี API · ไม่สามารถสร้างหรือ merge PR" action={<DemoBadge>Demo · Read-only · รอเชื่อมต่อ</DemoBadge>}/><Tabs items={Object.keys(rows).map(item=>({value:item,label:item}))} value={tab} onChange={setTab}/><Panel><h2>{tab}</h2>{rows[tab].map(item=><div className="search-row" key={item}><b>{item}</b><Badge>Demo repository data</Badge></div>)}</Panel></>; }
export function News() { const [filter,setFilter]=useState("ทั้งหมด"); const [saved,setSaved]=useState<number[]>([]); const toast=useToast(); const items=filter==="ทั้งหมด"?newsItems:newsItems.filter(item=>item.tag===filter); return <><Heading eyebrow="DEV NEWS · DEMO" title="อัปเดตที่ควรรู้" text="Mock summaries · ไม่มี RSS/API call" action={<DemoBadge/>}/><Tabs label="ตัวกรองข่าว" items={["ทั้งหมด","AI","Web","Security"].map(item=>({value:item,label:item}))} value={filter} onChange={setFilter}/><div className="news-grid">{items.map(item=><Card as="article" key={item.id}><Badge tone="brand">{item.source} · {item.tag}</Badge><h2>{item.title}</h2><p>{item.summary}</p><Button variant="ghost" onClick={()=>{setSaved(current=>[...new Set([...current,item.id])]);toast("บันทึกข่าวไว้ใน demo แล้ว")}}>{saved.includes(item.id)?"✓ Saved locally":"＋ Save locally"}</Button></Card>)}</div></>; }
