"use client";

import { MarkerType } from "@xyflow/react";
import { Button, FormField, Input, Select, Textarea } from "@/components/ui";
import type { FlowEdge, FlowNode } from "@/lib/flowchart/flowchart-types";

export function FlowchartPropertiesPanel({ node, edge, onNodeChange, onEdgeChange, onDuplicate, onDelete }: { node?: FlowNode; edge?: FlowEdge; onNodeChange: (data: FlowNode["data"]) => void; onEdgeChange: (patch: Partial<FlowEdge>) => void; onDuplicate: () => void; onDelete: () => void }) {
  const edgeLabel = typeof edge?.label === "string" || typeof edge?.label === "number" ? String(edge.label) : "";
  const edgeColor = typeof edge?.style?.stroke === "string" ? edge.style.stroke : "#64748b";
  return <aside className="flow-properties"><h2>Properties</h2>{node ? <><span className="flow-type-label">{node.type}</span><FormField label="ข้อความ"><Input value={node.data.label} onChange={event => onNodeChange({ ...node.data, label: event.target.value })} /></FormField><FormField label="คำอธิบาย"><Textarea rows={4} value={node.data.description ?? ""} onChange={event => onNodeChange({ ...node.data, description: event.target.value })} /></FormField><div className="flow-color-fields"><FormField label="สีพื้น"><Input type="color" value={node.data.backgroundColor ?? "#ffffff"} onChange={event => onNodeChange({ ...node.data, backgroundColor: event.target.value })} /></FormField><FormField label="สีกรอบ"><Input type="color" value={node.data.borderColor ?? "#789488"} onChange={event => onNodeChange({ ...node.data, borderColor: event.target.value })} /></FormField></div><Button size="sm" variant="ghost" onClick={() => { const data = { ...node.data }; delete data.backgroundColor; delete data.borderColor; onNodeChange(data); }}>คืนค่าสีเริ่มต้น</Button><div className="flow-property-actions"><Button onClick={onDuplicate}>ทำสำเนา</Button><Button variant="danger" onClick={onDelete}>ลบ</Button></div></> : edge ? <><span className="flow-type-label">เส้นเชื่อม</span><FormField label="ข้อความบนเส้น"><Input value={edgeLabel} placeholder="เช่น Yes, No" onChange={event => onEdgeChange({ label: event.target.value })} /></FormField><FormField label="รูปแบบเส้น"><Select value={edge.type ?? "smoothstep"} onChange={event => onEdgeChange({ type: event.target.value })}><option value="smoothstep">โค้งเข้ามุม</option><option value="bezier">เส้นโค้ง</option><option value="straight">เส้นตรง</option><option value="step">หักมุม</option></Select></FormField><div className="flow-color-fields"><FormField label="สีเส้น"><Input type="color" value={edgeColor} onChange={event => onEdgeChange({ style: { ...edge.style, stroke: event.target.value } })} /></FormField><FormField label="ความหนา"><Select value={String(edge.style?.strokeWidth ?? 2)} onChange={event => onEdgeChange({ style: { ...edge.style, strokeWidth: Number(event.target.value) } })}><option value="1">บาง</option><option value="2">ปกติ</option><option value="3">หนา</option><option value="5">หนามาก</option></Select></FormField></div><label className="flow-check"><input type="checkbox" checked={Boolean(edge.markerEnd)} onChange={event => onEdgeChange({ markerEnd: event.target.checked ? { type: MarkerType.ArrowClosed, color: edgeColor } : undefined })} /> แสดงหัวลูกศร</label><label className="flow-check"><input type="checkbox" checked={Boolean(edge.animated)} onChange={event => onEdgeChange({ animated: event.target.checked })} /> แสดงการเคลื่อนไหว</label><Button variant="danger" onClick={onDelete}>ลบเส้น</Button></> : <p>เลือก Node หรือเส้นเพื่อปรับแต่ง ลากจากจุดเชื่อมด้านใดก็ได้เพื่อสร้างเส้น</p>}</aside>;
}
